name: Unit test the plugins
on: [workflow_call]
jobs:

  Pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: install repo
        run: |
          pip install -e .[dev]
      - name: run pytest
        run: |
          pytest ./tests/extension_tests